### ISSUE TITLE
Code release

### ISSUE THREAD

**Issue by Sharpiless** [caiyuanhao1998/SAX-NeRF#1]
Great work! Are there any plans to release the code?

**Comment by caiyuanhao1998** [comment]
Yes, off course. We are going to release code, pre-trained weights, reconstructed results, our collected data, training logs, visualization scripts, etc. once our paper has been accepted. I will inform you at that time.

Thanks for your interests.

**Comment by JixiangChen-Jimmy** [comment]
Any news for the releasing plan?

**Comment by caiyuanhao1998** [comment]
> Any news for the releasing plan?

I will release the code before the start date of CVPR 2024 (2024.06.17). Stay tuned. Thanks for your patience

**Comment by caiyuanhao1998** [comment]
Hi, all, code, models, logs, and data have been released. Have fun :)
