### ISSUE TITLE
Curiosity | Performance on dynamic data

### ISSUE THREAD

**Issue by jaykshirsagar05** [caiyuanhao1998/SAX-NeRF#11]
Hi Authors,

Thank you for deploying the code. It's really helpful to have all architectures in one place. I have a question about how your models would perform on dynamic data. Is it possible to incorporate a temporal aspect into the existing architecture, considering that my data modality changes with time?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Our two designs, Lineformer and MLG sampling are general. They can be plugged in other NeRF-based methods. As for the dynamic scenes. I suggest you combine the dynamic design with our proposed techniques. The D-NeRF is an example: D-NeRF: Neural Radiance Fields for Dynamic Scenes, https://github.com/albertpumarola/D-NeRF
