### ISSUE TITLE
image saving problem

### ISSUE THREAD

**Issue by meimeimeime** [caiyuanhao1998/SAX-NeRF#12]
when using imageio to save image ,P.S. in this sentence specificlly `iio.imwrite(osp.join(proj_pred_origin_dir, f"proj_pred_{str(i)}.png"), (cast_to_image(projs_pred[i])*255).astype(np.uint8))`
there comes the problem of Can't write images with one color channel. How can this be solved?like using cv instead?

**Comment by caiyuanhao1998** [comment]
Did you install the specific imageio package as we suggested?
Please show the screenshot of the bug. I can help you check it

If you find our repo useful, please help us star it

**Comment by meimeimeime** [comment]
Dear Cai:
&nbsp; Thanks for reply!I have solved this by using cv2 instead.
Wish you all good!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "caiyuanhao1998/SAX-NeRF"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年7月24日(星期三) 凌晨1:06
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [caiyuanhao1998/SAX-NeRF] image saving problem (Issue #12)





 
Did you install the specific imageio package as we suggested?
 Please show the screenshot of the bug. I can help you check it
 
If you find our repo useful, please help us star it
