### ISSUE TITLE
Hash encoder requires CUDA v11.3

### ISSUE THREAD

**Issue by BiTaNannnnn** [caiyuanhao1998/SAX-NeRF#16]
**So Nice to share the code.**
I tried to follow the author's instructions to install CUDA = v11.3, and then followed a series of environment installations. But I encountered an error:

“
    from .backend import _backend
  File "/ai4hh/ai4h/mawen/Project/SAX-NeRF-master/src/encoder/hashencoder/backend.py", line 18, in <module>
    _backend = load(name='_hash_encoder',
  File "/home/wenma/anaconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1144, in load return _jit_compile(
  File "/home/wenma/anaconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1357, in _jit_compile
    _write_ninja_file_and_build_library(
  File "/home/wenma/anaconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1469, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "/home/wenma/anaconda3/envs/sax_nerf/lib/python3.9/site-packages/torch/utils/cpp_extension.py", line 1756, in _run_ninja_build
    raise RuntimeError(message) from e

**RuntimeError: Error building extension '_hash_encoder': [1/3] /usr/bin/nvcc
nvcc fatal   : Unsupported gpu architecture 'compute_86'
ninja: build stopped: subcommand failed.**
”

**And**
ninja --version = 1.11.1.git.kitware.jobserver-1
gcc & g++ version = 9.4.0
nvcc: 11.3

Who can save this child...

**Comment by BiTaNannnnn** [comment]
When I change the backend.py extra_cuda_cflags=[
                    '-O1',
                    '-arch=sm_70',
                    '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__' # undefine flags, necessary!
                ],  
 It also has the same error.

If I change the '-arch=sm_70' to '-arch=sm_75/80/85' 
It will show this:
"
nvcc fatal   : Value 'sm_80' is not defined for option 'gpu-architecture'
ninja: build stopped: subcommand failed.
"

**Comment by caiyuanhao1998** [comment]
The error you encountered, "nvcc fatal: Unsupported gpu architecture 'compute_86'," indicates that the NVIDIA CUDA Compiler (nvcc) does not support the GPU architecture specified for compilation, which in this case is 'compute_86'. This issue can arise if you're using a CUDA toolkit version that does not support the specific compute capability of your GPU. 

Please determine the compute capability of your GPU and check if it aligns with the CUDA version installed

If you find our repo useful, please help us star it. Thanks.

**Comment by BiTaNannnnn** [comment]
The final solution to this problem is Ninja version = 1.10.0. 
I have tried 1.12 and 1.8 before and the problem still exists. 

Today I tried version 1.10.0/1.10.2 and it was solved successfully.

**Comment by caiyuanhao1998** [comment]
Hi, really happy to see that you have fixed the problem. Good luck :)
