### ISSUE TITLE
Training Time Comparison

### ISSUE THREAD

**Issue by 1999kevin** [caiyuanhao1998/SAX-NeRF#17]
Nice Work!

I have run your code on the Chest-50 data. I find that your proposed LineFormer requires much more training time than other methods. Specifically, your LineFormer requires about 6 hours for 1500 epochs while Naf only requires about 15 minutes. 

Could you please provide more details about why LineFormer requires a much longer training process? Is it because LineFormer has more parameters or is it related to MLG sampling strategy?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

Two reasons: (i) The multi-head self-attention (ii) The sampling strategy
