### ISSUE TITLE
Custom dataset 

### ISSUE THREAD

**Issue by leejngmn** [caiyuanhao1998/SAX-NeRF#19]
Hello!
I appreciate your research.
Your research has led to some interesting collaborations.

The data we use is too big, so we are trying to reshape it to 256*256*256 size like the sample you provided. 
However, if we set it to 2048*2048*2160, an error occurs. 
What does the z-axis mean here? What should go in place of 2160?

In addition, are there any parameters to keep in mind when using a custom dataset?
Below is our Dicom data.

###
Scan
Scan mode:	CT
2048		Number of Detector Elements 
2160		CT: Number of Projections
19		DR: Number of Lines
1		Linebinning Settings
1		Pixelbinning Settings
Measurement extension:	none
1		Multi-Scan: Number of Slices
184.20		Multi Slice: Distance between two Slices [mm]
2.14		Magnification (Object Center) 
0.09366268	2D-Pixel Size [mm]
0.09366286	3D-XY-Pixel Size [mm]
0.09514938	3D-Z-Pixel Size [mm]
1		CT: Number of Slices

Detector
Detector Type:	Y.XRD1621
409.60		Detectorlength

Reconstruction
2048		Number of actual Detector Pixel
2048		Image Dimension
2016		Number of Z-slices
2160		Number of Projections
0.00		Rotational Offset in degree
Dose Rate Correction:	on
0.00000000	Center Offset [Pixel]
0.00000000	Center Offset [mm]
1.00		Convolution Coefficient
409.60		ROI [mm]

Axis
257.12		X-Axis: Measurement Position [mm]
750.00		Y-Axis: Measurement Position [mm]
1225.60		YD-Axis: Measurement Position [mm]
281.00		ZS-Axis: Measurement Position [mm]
1225.60		Focus-Detector distance [mm]
651.64		Object-Detector distance [mm]
573.97		Focus-Object distance [mm]
500.00		Integration Time [ms] for CT and DR

X-Ray
X-Ray-Tube:	MF X-Ray-Tube
Tube head:	D-Target FXE 225.99 (48)
185.00		Voltage [kV]
0.49		Current [mA]
Focus:		small
TXI:	on
SecondTubeHead:	off

Filter
Al	0.50		[mm]
Cu	0.00		[mm]
Sn	0.00		[mm]
Fe	0.00		[mm]

Remarks

**Comment by leejngmn** [comment]
This is a config based on Dicom data.
Is there anything wrong?
I wonder if the 2D-Pixel Size in X,Y direction is correct, and how can I find out the Accuracy of FWD proj value.

Thank you so much!

# Parameters to setup CT simulation.

# dataset
numTrain: 50
numVal: 50

# System configuration
DSD: 1225.60  # Distance Source Detector      (mm)
DSO: 573.97  # Distance Source Origin        (mm)

# Detector parameters
nDetector: # Number of pixels              (px)
- 2048 
- 2048 
dDetector: # Size of each pixel            (mm)
- 0.09366268  # 2D-Pixel Size in X direction
- 0.09366268  # 2D-Pixel Size in Y direction

# Image parameters
nVoxel: # Number of voxels              (vx)
- 2048  # X direction (Image Dimension)
- 2048  # Y direction (Image Dimension)
- 2160  # Z-slices
dVoxel: # size of each voxel            (mm)
- 0.09366286  # 3D-XY-Pixel Size in X direction
- 0.09366286  # 3D-XY-Pixel Size in Y direction
- 0.09514938  # 3D-Z-Pixel Size

# Offsets
offOrigin: # Offset of image from origin   (mm)
- 0 # x direction
- 0 # y direction
- 0 # z direction
offDetector: # Offset of Detector (only in two direction)            (mm)
- 0 # u direction
- 0 # v direction

# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj          (vx/sample)

# Mode
mode: cone # X-ray source mode parallel/cone
filter: null

# Angles
totalAngle: 360.0 # Total angle  (degree)
startAngle: 0.0 # Start angle (degree)
randomAngle: False

# CT
convert: True
rescale_slope: 1.0
rescale_intercept: 0.0
normalize: True

# Noise
noise: 0

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

I suggest you first downscale the CT volume from  2048 x 2048 x 2160 to 256 x 256 x 270. The z-axis does not have any physical meaning. But I suggest you visualize the data to make sure it seems plausible, that is, you can tell it from the projection. Or you'd better rotate the axis until it looks plausible. Just follow our instruction about how to use `TIGRE` toolbox and use our data generation to synthesize the pickle file containing the 2D projections.

Hope this information may help :)

**Comment by caiyuanhao1998** [comment]
The parameters of config should be set in the yaml file and the config setting of the data generation

**Comment by leejngmn** [comment]
Your comments were very helpful. 
Thank you so much for your kind comments
I succeeded in downscaling.

However, when I visualized the data both before and after downscaling, it seems that there is a problem with the raw data.
![20240919_213953](https://github.com/user-attachments/assets/9d2b085e-e2d2-4d11-ba20-1f138a35dc18)
![20240919_213909](https://github.com/user-attachments/assets/6cefedbb-2a6c-4455-8d14-a4c4c83de8f5)


The pancreas data you provided is visualized well, but will it be effective if I rotate the axis?
There is no axis-related rotate parameter in the config, so what is being rotated?

**Comment by leejngmn** [comment]
> Hi, thanks for your interest.
> 
> I suggest you first downscale the CT volume from 2048 x 2048 x 2160 to 256 x 256 x 270. The z-axis does not have any physical meaning. But I suggest you visualize the data to make sure it seems plausible, that is, you can tell it from the projection. Or you'd better rotate the axis until it looks plausible. Just follow our instruction about how to use `TIGRE` toolbox and use our data generation to synthesize the pickle file containing the 2D projections.
> 
> Hope this information may help :)

Your comments were very helpful.
Thank you so much for your kind comments
I succeeded in downscaling.

However, when I visualized the data both before and after downscaling, it seems that there is a problem with the raw data.
The pancreas data you provided is visualized well, but will it be effective if I rotate the axis?
There is no axis-related rotate parameter in the config, so what is being rotated?
![20240919_213953](https://github.com/user-attachments/assets/f3f673e2-079a-4118-9092-796aa8aee9c2)
![20240919_213909](https://github.com/user-attachments/assets/25157655-4f96-421b-a11d-5438c5ac3c62)
