### ISSUE TITLE
Question regarding the X3D dataset.

### ISSUE THREAD

**Issue by kalelpark** [caiyuanhao1998/SAX-NeRF#2]
I appreciate the excellence of your research. 
Upon reading the paper, I was wondering when I could download the X3D dataset used in the paper. 
Or could you provide information on where the dataset can be downloaded?

Thank you for good research.

**Comment by caiyuanhao1998** [comment]
We will release the code, model, and data before the start date of CVPR 2024 (2024.06.19).
I will let you know then. Stay tuned :)
Thanks for your interests

**Comment by caiyuanhao1998** [comment]
hi，data was released
