### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by xuyaojian123** [caiyuanhao1998/SAX-NeRF#20]
首先非常感谢您出色的开源工作，因为刚开始做这个研究，有一些问题想请教您。
1、我清楚NSV任务，只需要输入不同的camera pose就可以渲染出不同的图像。但我不清楚CT Reconstruction是什么任务，它和论文中NSV有什么区别吗？作者能详细解释一下吗？
2、请问一下X-ray的投影图像，和可见光形成的图像，是一样的预处理过程的嘛？直接输入到colmap中得到camera pose和相机内参嘛？或者X-ray图像是需要通过特殊的处理嘛才能得到内外参嘛？
可能有些表达不清楚，请见谅，期待您的回复，谢谢！

**Comment by xuyaojian123** [comment]
3、在你CT Reconstruction任务中，为什么评价指标还是和NSV一样的PSNR和SSIM，而不是Chamfer Distance等评价3D的指标？

**Comment by caiyuanhao1998** [comment]
你好，感谢关注

1. CT Reconstruction 就是把 3D 的点的 density 给重建出来，而不是去渲染 2D 上的投影

2. 不一样的。X-ray 如果用 colmap 来跑的话，速度慢且效果不太好。我的算法使用了一种非常简单快速的初始化方法 ACUI，是 SfM-free 的

3. 我把 CT volume 离散化后切成一片片的 2D 图像了

**Comment by xuyaojian123** [comment]
> 你好，感谢关注
> 
> 1. CT Reconstruction 就是把 3D 的点的 density 给重建出来，而不是去渲染 2D 上的投影
> 2. 不一样的。X-ray 如果用 colmap 来跑的话，速度慢且效果不太好。我的算法使用了一种非常简单快速的初始化方法 ACUI，是 SfM-free 的
> 3. 我把 CT volume 离散化后切成一片片的 2D 图像了

感谢您的回答！我昨天给你发了QQ和Gmail邮件，希望添加一下您的联系方式，能和你有更多的请教和交流。

**Comment by caiyuanhao1998** [comment]
在 issue 里面问嘛，可能你遇到的问题别人也会遇到，要是有人天天微信上来问我，我会觉得有点烦，hhh
我会定期来看 issue，正常提问的都会回答一下的

**Comment by xuyaojian123** [comment]
好滴，谢谢
