### ISSUE TITLE
torch.utils.cpp_extension  loading issue

### ISSUE THREAD

**Issue by hws203** [caiyuanhao1998/SAX-NeRF#23]
@caiyuanhao1998 I can see that your backend.py includes  load(name='_hash_encoder',,,,) , but after call this loading function for torch extension, there is some stop, so no more progress at this point.  Please give me some guide about this issue.  Should I compile                     'hashencoder.cu', 'bindings.cpp' at first and make some binary file for this function or  torch_extension do this automatically? I am using windows 10  with anaconda(version conda 23.3.1).

**Comment by caiyuanhao1998** [comment]
This issue may be caused by the windows OS. I suggest you use the ubuntu system.

**Comment by hws203** [comment]
Yes, it is related to OS issue,  Below is my step to solve this issue.

1. set gpu_ids =0  from 6.
2. set CUDA_HOME="CUDA_PATH=C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.7" which is last installed version at my windows OS. 
3. save hashencoder.cuda and bindings.cpp with unicode type encoding by Visual studio.
4. comments out  os.remove(self.lock_file_path) line at baton.py file(in C:\ProgramData\Anaconda3\envs\sax_nerf\Lib\site-packages\torch\utils).

**Comment by WMSIF** [comment]
Evaluating: load(name='_hash_encoder',
                extra_cflags=['-O3'], # '-std=c++17'
                extra_cuda_cflags=[
                    '-O3',
                    '-U__CUDA_NO_HALF_OPERATORS__', '-U__CUDA_NO_HALF_CONVERSIONS__', '-U__CUDA_NO_HALF2_OPERATORS__', # undefine flags, necessary!
                ], # '-arch=sm_70'
                sources=[os.path.join(_src_path, 'src', f) for f in [
                    'hashencoder.cu',
                    'bindings.cpp',
                ]],
                ) did not finish after 3.00 seconds.
This may mean a number of things:
- This evaluation is really slow and this is expected.
    In this case it's possible to silence this error by raising the timeout, setting the
    PYDEVD_WARN_EVALUATION_TIMEOUT environment variable to a bigger value.

- The evaluation may need other threads running while it's running:
    In this case, it's possible to set the PYDEVD_UNBLOCK_THREADS_TIMEOUT
    environment variable so that if after a given timeout an evaluation doesn't finish,
    other threads are unblocked or you can manually resume all threads.

    Alternatively, it's also possible to skip breaking on a particular thread by setting a
    `pydev_do_not_trace = True` attribute in the related threading.Thread instance
    (if some thread should always be running and no breakpoints are expected to be hit in it).

- The evaluation is deadlocked:
    In this case you may set the PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT
    environment variable to true so that a thread dump is shown along with this message and
    optionally, set the PYDEVD_INTERRUPT_THREAD_TIMEOUT to some value so that the debugger
    tries to interrupt the evaluation (if possible) when this happens.
