### ISSUE TITLE
how to config laminography(oblique ct)case data generation at yml file ?

### ISSUE THREAD

**Issue by hws203** [caiyuanhao1998/SAX-NeRF#25]
@caiyuanhao1998 Could you guide me how to config  below yml file contents for my oblique ct case(40 degree) data generation?
I can not see any oblique angle degree at your yml config file.

///////////////////////////////////////////////////////////////////////////////////////////////
# Parameters to setup CT simulation.
# dataset
numTrain: 50
numVal: 50
# System configuration
DSD: 1500.0  # Distance Source Detector      (mm)
DSO: 1000.0  # Distance Source Origin        (mm)
# Detector parameters
nDetector: # Number of pixels              (px)
- 1024
- 1024 
dDetector: # Size of each pixel            (mm)
- 1.0
- 1.0
# Image parameters
nVoxel: # Number of voxels              (vx)
- 512
- 512
- 512 
dVoxel: # size of each voxel            (mm)
- 0.9766
- 0.9766
- 0.9766
# space directions: (0.9766,0,0) (0,0.9766,0) (0,0,1.25)
# Offsets
offOrigin: # Offset of image from origin   (mm)
- 0 # x direction
- 0 # y direction
- 0 # z direction
offDetector: # Offset of Detector (only in two direction)            (mm)
- 0 # u direction
- 0 # v direction
# Auxiliary
accuracy: 0.5 # Accuracy of FWD proj          (vx/sample)
# Mode
mode: cone # X-ray source mode parallel/cone
filter: null
# Angles
totalAngle: 180.0 # Total angle  (degree)
startAngle: 0.0 # Start angle (degree)
randomAngle: False
# CT
convert: True
rescale_slope: 1.0
rescale_intercept: 0.0
normalize: True
# Noise
noise: 0
///////////////////////////////////////////////////////////////////////////////////////////////

**Comment by caiyuanhao1998** [comment]
It seems that you just need to input these parameters into the data generation config file (`.yaml`) in `SAX-NeRF/dataGenerator/raw_data/aneurism/config.yml` and then execute my data generation script.

**Comment by hws203** [comment]
If i use your script then the prj image looks different from a real one. Coz it is oblique projection.

**Comment by caiyuanhao1998** [comment]
Could you please show it?

**Comment by hws203** [comment]
1. simulation projection image
<img width="732" alt="js-sim01" src="https://github.com/user-attachments/assets/208a0455-c1ba-4ff7-9fb0-a26ec932c1f6">

2. real projection image
<img width="712" alt="real-prj" src="https://github.com/user-attachments/assets/7dd22038-3696-4a49-b212-22b3f74d9e8c">

**Comment by hws203** [comment]
3.Below is volume image with z-axis and x-axis
<img width="1532" alt="vol3" src="https://github.com/user-attachments/assets/362a7a35-4148-4d31-b94b-315a6890b2a4">

**Comment by caiyuanhao1998** [comment]
It seems that you did not align the CT volume. Try to adapt some parameters and visualize the projections for debugging

**Comment by hws203** [comment]
I adapt some  config param for data generation, and I can see a little better projection which looks more similar to a real one.
But there are still some gap as like it is projected on the standard cone beam geometry  not laminography.
Below are the second project images.

<img width="1068" alt="project_js" src="https://github.com/user-attachments/assets/830b9bd2-a0e5-4b22-8214-929bfd2cb7b2">

**Comment by hws203** [comment]
Should I tilt the volume image for laminography(tilt=40, degree) ?

**Comment by hws203** [comment]
@caiyuanhao1998   Below is my test run result it looks too low ssim score. Could you give why this result happens ?

I used customer data with your own data generation script and your train/test too. 

<img width="1120" alt="result" src="https://github.com/user-attachments/assets/0df9bfd0-d25c-45fa-b509-f27c9d5cce6f">
