### ISSUE TITLE
angle2pose函数求的是c2w矩阵，还是w2c矩阵？

### ISSUE THREAD

**Issue by xuyaojian123** [caiyuanhao1998/SAX-NeRF#27]
在X-Gaussian中，我看返回的是c2w矩阵
`c2w = angle2pose(geometry.DSO,angles[idx])`
但是，在Sax-NeRF我看你函数的注释是w2c矩阵？
![image](https://github.com/user-attachments/assets/e79440fb-4e2b-4d05-b1dd-68eb85d65a7c)

**Comment by caiyuanhao1998** [comment]
c2w

**Comment by xuyaojian123** [comment]
还有想问下，您对NeAT论文的数据集，也是用同样的方法求c2w矩阵吗？NeAT论文的数据集使用的是尼康工业CT扫描仪（a Nikon industrial CT scanner）获得的.xtekct元数据，同样也适用这个方法求c2w吗？而且NeAT代码过于复杂（C++写的，看不懂），不清楚它是怎么求camera pose的。
