### ISSUE TITLE
How to evaluate？

### ISSUE THREAD

**Issue by xuyaojian123** [caiyuanhao1998/SAX-NeRF#28]
请问一下，比如对于Teapot场景，它的原始数据只有它对应的投影图像和CT扫描的元配置文件.xtekct。那么我如何评价重建后的效果？因为原始数据中没有真实的三维volume CT数据。
![image](https://github.com/user-attachments/assets/cd749dd8-deaf-4472-926d-689f2136800f)

![image](https://github.com/user-attachments/assets/e4f677fa-15e4-4c42-9716-216542e40977)

![image](https://github.com/user-attachments/assets/6088834f-7390-4454-8d81-5136a2fa68e0)

**Comment by caiyuanhao1998** [comment]
我记得我有提供 teapot 的 CT volume 呀，可以使用我提供的 teapot 的 CT volume 来 evaluate
