### ISSUE TITLE
How to evaluate CT volume？

### ISSUE THREAD

**Issue by xuyaojian123** [caiyuanhao1998/SAX-NeRF#29]
真实的三维CT volume数据是 img.mat，你通过`def get_voxels(self, geo: ConeGeometry)`函数得到三维体素网格的坐标，然后输入网络得到坐标对应的density。那请问一下get_voxels函数得到的三维体素坐标和img.mat是如何对应上的，他们对应的是同一个世界坐标位置吗？

![image](https://github.com/user-attachments/assets/37df918c-d454-4caf-bcaf-4c8339837747)

**Comment by caiyuanhao1998** [comment]
`img.mat` 并没有坐标，坐标是通过 get_voxels 函数得到的，这个是可以自己设置的
