### ISSUE TITLE
About your strategies

### ISSUE THREAD

**Issue by Zhentao-Liu** [caiyuanhao1998/SAX-NeRF#3]
A great work on CT reconstruction.
I wanna ask a question. The strategies you developed in your paper: lineformer and MLG, are they suitable for natural scenes, i.e. RGB NeRF? It seems that they are not specific for X-rays.

**Comment by Zhentao-Liu** [comment]
I am still confusing. Should we cast some rays at the blank area (where mask=0)? Otherwise, how did the model get to know whether its empty? Wouldnt be blurry?

**Comment by caiyuanhao1998** [comment]
For CT, no. It's very sparse. According to the experiments, the rendered projections are not blurry

**Comment by Zhentao-Liu** [comment]
How do you achieve non-overlap patch sampling in the mask image? Could you simply describe it?

**Comment by Zhentao-Liu** [comment]
How about apply mamba to replace your transformer block?

**Comment by caiyuanhao1998** [comment]
it is interesting. I just released code. Feel free to have a try
