### ISSUE TITLE
Passing viewpoints instead of CT volumes

### ISSUE THREAD

**Issue by marcosolime** [caiyuanhao1998/SAX-NeRF#30]
If I have understood correctly, your method takes as input a CT scan of shape (width, height, depth), and extracts the views with TIGRE toolkit. May I pass the model directly the projections of the object, as well as the angles, if I do not have a CT scan volume? My views are x-ray images from -90 to 90 degrees around the object. Do I need to perform some kind of preprocessing on my input images? Thank you.

**Comment by caiyuanhao1998** [comment]
If your data are just real X-ray images, I suggest you initialize the scanner parameters in the dataloader. 

https://github.com/caiyuanhao1998/SAX-NeRF/blob/master/src/dataset/tigre_mlg.py#L42

And then feed the angles and projections into the dataloader.

Hope this can help you.
