### ISSUE TITLE
how to handle TIFF format?

### ISSUE THREAD

**Issue by hei-xiaohuihui** [caiyuanhao1998/SAX-NeRF#34]
I only have tif format files, how should I handle them to input for training?

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

If the TIFF is the CT volume, please extract the 3D matrix and use our data generation code to synthesize training data pairs.

If the TIFF is the projection, please set the parameters of X-ray scanner in our dataloader script to load the training data pairs.
