### ISSUE TITLE
test.py error on Win11 OS

### ISSUE THREAD

**Issue by WMSIF** [caiyuanhao1998/SAX-NeRF#37]
我在win11系统上运行test.py时，照着前面hws203老哥的步骤重新配置了文件，但是还是遇到了load函数进程卡住无法继续的问题，然后我在vscode的调试控制台重新运行了load语句，出现了以下报错，请问您方便看看这是什么原因导致的吗，不胜感激！
Evaluating: _backend = load( name=name, extra_cflags=extra_cflags, extra_cuda_cflags=extra_cuda_cflags, sources=sources) did not finish after 3.00 seconds.
This may mean a number of things:
- This evaluation is really slow and this is expected.
    In this case it's possible to silence this error by raising the timeout, setting the
    PYDEVD_WARN_EVALUATION_TIMEOUT environment variable to a bigger value.

- The evaluation may need other threads running while it's running:
    In this case, it's possible to set the PYDEVD_UNBLOCK_THREADS_TIMEOUT
    environment variable so that if after a given timeout an evaluation doesn't finish,
    other threads are unblocked or you can manually resume all threads.

    Alternatively, it's also possible to skip breaking on a particular thread by setting a
    `pydev_do_not_trace = True` attribute in the related threading.Thread instance
    (if some thread should always be running and no breakpoints are expected to be hit in it).

- The evaluation is deadlocked:
    In this case you may set the PYDEVD_THREAD_DUMP_ON_WARN_EVALUATION_TIMEOUT
    environment variable to true so that a thread dump is shown along with this message and
    optionally, set the PYDEVD_INTERRUPT_THREAD_TIMEOUT to some value so that the debugger
    tries to interrupt the evaluation (if possible) when this happens.

**Comment by caiyuanhao1998** [comment]
感觉可以把 timeout 的时间调得大一些。不过我还是建议不要用 windows 系统来跑，建议你用 ubuntu 系统，能够避免很多不必要的 bug
