### ISSUE TITLE
train

### ISSUE THREAD

**Issue by he0713** [caiyuanhao1998/SAX-NeRF#39]
I have the following situation when using the training commands you provided
![train](https://github.com/user-attachments/assets/6bf99ad3-dab7-4554-9e65-4a69723baece)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest,

This problem is caused by the windows operation system

I suggest you use ubuntu system to run our code

If you find our repo useful, please help us star it, thanks :)

**Comment by he0713** [comment]
Thank you for your reply

**Comment by he0713** [comment]
I'm using exactly what you call the ubuntu system

**Comment by wujh0ustc** [comment]
This is caused by Torch's error in reading the architecture supported by your CUDA. I fixed this by setting an environment variable:
`export TORCH_CUDA_ARCH_LIST="8.6"`
following the instructions here:
https://arnon.dk/matching-sm-architectures-arch-and-gencode-for-various-nvidia-cards/

**Comment by caiyuanhao1998** [comment]
Thanks for letting me know!
