### ISSUE TITLE
code

### ISSUE THREAD

**Issue by he0713** [caiyuanhao1998/SAX-NeRF#40]
Hellow，There is a mismatch between the settings in the paper and the settings in the code, and the paper says that the network structure is four LSAB and two fc layers. But there are only four layers in the code, and only two are LSAB and two are fc, so I can't match the code with the picture given in the paper.

**Comment by caiyuanhao1998** [comment]
Actually, we set the num_layers here to 4.

https://github.com/caiyuanhao1998/SAX-NeRF/blob/master/src/network/Lineformer.py#L308

So we use 4 LSABs

If you find our repo and my response useful, please help us star this repo, thanks :)

**Comment by he0713** [comment]
I can't push out four LSABs by following num_layers=4 in your code, as in
your code
https://github.com/caiyuanhao1998/SAX-NeRF/blob/95eed78be540b31df0e3b3bbde598d52d4f28e1f/src/network/Lineformer.py#L308
I can only push out the network structure composed of Linear, LSAB, Linear,
Linear, Linear.
