### ISSUE TITLE
About generating private datasets

### ISSUE THREAD

**Issue by shenao1994** [caiyuanhao1998/SAX-NeRF#5]
Hello! The img.mat file was missing when running generatedata_backpack.py. Could you upload this data, please? **FileNotFoundError: [Errno 2] No such file or directory: './dataGenerator/raw_data/backpack/img.mat'** In addition, if I want to use a nii.gz format CT file to generate a training set, what should I do? I found in the generatedata.py code that the input CT needs a dictionary, which contains a lot of information.

**Comment by caiyuanhao1998** [comment]
Hello, the `.mat` file is generated by running

```sh
cd dataGenerator
python data_vis_backpack.py
```

After producing the `.mat` file. Run

```sh
cd ..
python dataGenerator/generateData_backpack.py
```

If you start with nii.gz, I suggest you first read this file and then convert it into numpy. The following steps are the same as our processing pipeline in the provided code. We will provide more instances for reference. Stay tuned :)

**Comment by shenao1994** [comment]
> Hello, the `.mat` file is generated by running
> 
> ```shell
> cd dataGenerator
> python data_vis_backpack.py
> ```
> 
> After producing the `.mat` file. Run
> 
> ```shell
> cd ..
> python dataGenerator/generateData_backpack.py
> ```
> 
> If you start with nii.gz, I suggest you first read this file and then convert it into numpy. The following steps are the same as our processing pipeline in the provided code. We will provide more instances for reference. Stay tuned :)

Thank you very much. I thought data_vis_backpack.py was useless, so I stopped. My fault.
