### ISSUE TITLE
Testing FDK error No TIGREDataset_Traditional function 

### ISSUE THREAD

**Issue by ning-yuan** [caiyuanhao1998/SAX-NeRF#7]
Thanks for sharing your awesome project!
I try to run `python3 eval_traditional.py --algorithm fdk --category chest --config config/FDK/chest_50.yaml` . 
But retrun some error  
`Traceback (most recent call last):
  File "/workspace/SAX-NeRF/eval_traditional.py", line 9, in <module>
    from src.evaluator import Evaluator
  File "/workspace/SAX-NeRF/src/evaluator.py", line 5, in <module>
    from .dataset import TIGREDataset_Traditional as Dataset
ImportError: cannot import name 'TIGREDataset_Traditional' from 'src.dataset' (/workspace/SAX-NeRF/src/dataset/__init__.py)`
It seems like there is no function called TIGREDataset_Traditional。

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

I just uploaded the code of the data loader and fixed this bug

please have a try again :)

**Comment by ning-yuan** [comment]
> Hi, thanks for your interest.
> 
> I just uploaded the code of the data loader and fixed this bug
> 
> please have a try again :)

thanks sir. It works! By the way, it is possibel to have other raw data. Like chest ,  abdomen ,  foot and jaw  ?

**Comment by caiyuanhao1998** [comment]
Yes, for the raw data of chest, abdomen, foot, and jaw. Please download them from 

https://drive.google.com/drive/folders/1qiPWmhseEVC3vZ4SmYUmopsaC-yEKKXZ
