### ISSUE TITLE
Error with generating own data using TIGRE

### ISSUE THREAD

**Issue by ooonesevennn** [caiyuanhao1998/SAX-NeRF#8]
Hi, thanks for sharing this awesome project!

I have already generated .mat file.
However, when I try to run 'python dataGenerator/generateData_backpack.py', I got the following errors as shown below. I followed the steps for downloading and installing TIGRE exactly without any errors during those steps. Is there any effective way to solve this problem? Thanks a lot!

![image](https://github.com/caiyuanhao1998/SAX-NeRF/assets/95276096/e798b676-032d-40aa-a9d2-a832286c8c43)

**Comment by caiyuanhao1998** [comment]
Hi, thanks for your interest.

we suggest you use the Ubuntu operation system instead of the Windows system because the Windows system usually leads to some weird bugs.
