### ISSUE TITLE
 Raw data convert

### ISSUE THREAD

**Issue by Caocw6689** [caiyuanhao1998/SAX-NeRF#9]
Dear author,
 If my raw data are in nii format, how could I convert them to the suitable form for SAX-NeRF, or what parameters should  I stay the same?

**Comment by caiyuanhao1998** [comment]
The first step is to convert your data into a 3D matrix, the data type can be converted to `uint8` or `unit 16` in `numpy`. Then use our code and follow the introduction to generate the `.pickle` file.
